# Exercise 07: min-max rescaling

In all these exercises, **do not use for loops**!

In [6]:
import numpy as np

### Maximum over a two-dimensional array

Create a $5 \times 10$ array with random values between 0 and 1 and find the maximum values in the entire array, and in each column.

In [8]:
rng=np.random.default_rng()
matrix = rng.standard_normal(size=(5,10))

In [9]:
matrix.shape

(5, 10)

In [10]:
matrix

array([[-1.3608749 , -0.92838531, -0.11649572, -0.11359308,  0.05363768,
        -0.698791  , -0.44595841, -0.43077292,  0.47659475,  0.59378367],
       [-0.36011793,  0.14535038, -0.37313602,  0.10205607, -1.47548951,
        -0.1817305 , -1.32993637,  0.79639854, -1.1127516 , -0.47218979],
       [-1.96444353, -1.06308574,  0.07254392, -0.3393981 , -0.56868536,
        -0.84511469, -0.70112482, -0.00700473, -0.39889876,  1.21652935],
       [ 1.27165839,  1.07684066, -0.32464196,  1.47468525, -1.77970883,
         0.46947413,  0.86505409,  1.32423984,  1.07329553,  0.82109826],
       [-0.44859313, -0.94088068,  0.72249984,  0.23502506, -1.00944078,
         0.69056882,  0.86797307,  0.51075464, -0.09410202,  0.54526411]])

In [11]:
# your code here

### Data normalizaion / scaling

Let's consider the problem of data normalization/scaling:  in statistics and machine learning it is often desirable to convert data to a specified range, for example scale the data so that the values fall between 0 and 1, which is called [min-max rescaling](https://en.wikipedia.org/wiki/Feature_scaling#Rescaling_(min-max_normalization).  
Suppose you have a vector (or one dimensional array) of values `x`, then the min-max rescaled values are given by:
$$
x' = \frac{x-\min(x)}{\max(x) - \min(x)}
$$
For your exercise, first perform min-max rescaling over a one-dimensional array.  Next, assume you are given a two dimensional array, where you need to perform min-max rescaling **on each column separately**, i.e. apply the transformation above to each column separately. Test that your code works as expected (hint in a code cell below)!

In [51]:
rng=np.random.default_rng()

# one dimensional array:
x = rng.standard_normal(size=(50,))
# code for min-max rescaling of an array (one line of code)
print("OG: ", x)
x = (x - x.min(axis=0))/(x.max(axis=0) - x.min(axis=0))
print("New: ", x)
X=rng.standard_normal(size=(50,3))
# code for min-max rescaling of a 2-d array 
# can be done in one line of code 
# make sure you don't use for loops!
print("OG: ", X)
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
print("New: ", X)

OG:  [ 0.04188124 -0.05523691  0.60782092 -0.39069356  1.32761519 -0.83271958
 -0.67089547 -1.20189487  0.96299022  0.14979905 -1.49946371  0.17115899
  1.52102294 -1.60787145  1.82826954  0.02778    -0.45177556 -0.23709308
  1.14630751  0.87724737 -0.39876169 -1.36228155 -0.027765    0.23485108
 -1.72128953  0.87983126  1.11912424  1.24762875 -1.13763586 -0.69275982
 -1.27703893 -0.49926882  0.3520158  -0.07933556 -0.17553547  0.18854821
  0.3043013   0.24824362 -0.00273901 -1.27834493 -0.36210163 -0.14766812
 -0.65029647 -0.36343768 -0.64890106  0.60711796 -1.19232109  0.53819289
  0.22440515 -1.18408462]
New:  [0.49672952 0.46936889 0.65616895 0.37486233 0.85895309 0.25033249
 0.29592241 0.14632653 0.75622907 0.52713268 0.06249391 0.53315031
 0.91344091 0.03195272 1.         0.49275684 0.35765399 0.41813544
 0.80787416 0.73207315 0.37258933 0.10114157 0.47710842 0.55109397
 0.         0.7328011  0.80021595 0.8364189  0.16442991 0.28976267
 0.12515656 0.34427395 0.58410222 0.4625797 

To evaluate your code for min-max rescaling compute the following (assuming that your rescaled matrix is stored in a variable named `X_rescaled`):

```Python
print(X_rescaled.min(axis=0))
print(X_rescaled.max(axis=0))
```
What do you expect the output of these commands to be if you correctly performed min-max rescaling?

In [53]:
# test your code here:
print(X.min(axis=0))
print(X.max(axis=0))

[0. 0. 0.]
[1. 1. 1.]
