# CS 345 Exercise 4: vectors and dot products

**Instructions:** Complete the exercises in this notebook and submit it via Canvas.

In this exercise we will practice some of the concepts related to vectors and dot products.

In [3]:
import numpy as np

## Part 1: Unit vectors

Recall that a vector with a norm equal to 1 is called a **unit vector**.

Given an arbitrary vector $\mathbf{u}$ it is easy to make it into a unit vector by dividing by its norm, which is called *normalization*.


#### question 1

Write code for converting a vector, represented as a NumPy array to a unit vector.  Verify that the resulting vector is indeed a unit vector (how?)

In [41]:
def normalize(vector):
    norm = np.square(vector)
    norm = np.sum(norm)
    norm = np.sqrt(norm)
    vector = vector / norm
    return vector

# verify that the result of normalize is indeed a unit vector
test_vector = np.array([3,4,5])
print(test_vector)
test_vector = normalize(test_vector)
print(test_vector)

[3 4 5]
[0.42426407 0.56568542 0.70710678]


#### question 2

Write down an expression for a $d$ dimensional unit vector whose components are all equal.  Demonstrate that it is indeed a unit vector.

vector = [x, x, ..., x]. Unit vector is vector divided by norm. If all x are equal, then the norm would be x / sqrt(x^2) = x / x = 1 which is the unit vector length.

## Part 2:  the * operator

* We have already seen how the `*` operator functions between a scalar and a vector (one dimensional array) in NumPy.  It also works between vectors.  However, the vectors need to be of the same size.  Your task is to explore what the multiplication operator does when applied between one dimensional arrays, and describe the operation in words.

In [53]:
## define two one-dimensional numpy arrays of the same size and 
## check what is the result of multiplying them using the * operator

vector1 = np.array([1, 2, 3])
vector2 = np.array([2, 3, 4])

print(vector1, "\n", vector2, "\n", vector1 * vector2)

[1 2 3] 
 [2 3 4] 
 [ 2  6 12]


Each index is multiplied together linearly

## Part 3: dot products and angles between vectors

### question 1

What is the angle between orthogonal vectors?  Explain!


The definition of orthogonality is the involvement of right angles and perpendicularity, so the angle would be 90 degrees.

### question 2

What can you say about the angle between vectors that have positive coefficients?


The angle between vectors that have positive coefficients is less than 90 degrees but greater than 0 degrees since they would both be pointing in the same direction and the cosine similarity between these vectors would be between 0 and 1.

### question 3

Express the norm of a vector as a dot product.


If v is a vector of any dimension, then its norm could be a dot product shown as "norm = sqrt(v^T * v)" where ^T is transpose notation.

To help you, here is an [animation of the sine and cosine functions](https://www.desmos.com/calculator/cpb0oammx7) that nicely illustrates the geometry these functions.

### Part 4:  the cosine between vectors


Use NumPy to write code that computes the cosine between two vectors with an arbitrary number of dimensions.
Use your code to compute the angle between

$$
\mathbf{u} = \begin{pmatrix}
1 \\ 0 \\ -1 \\ 2
\end{pmatrix}, \qquad  \mathbf{v} = \begin{pmatrix}
3 \\ 1 \\ 0 \\ 1
\end{pmatrix}
$$

In [89]:
def cosine(u, v) :
    numerator = np.dot(u,v)
    denominator = np.linalg.norm(u) * np.linalg.norm(v)
    return numerator / denominator

result = cosine(vector1, vector2)
print(vector1, "\n", vector2, "\n", result)

[1 2 3] 
 [2 3 4] 
 0.9925833339709303
